name: Rust
run-name: ${{ github.actor }}

on: 
  pull_request:
    branches:
      - develop

env:
  RUST_VERSION: 1.55.0
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -name: Format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
